version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      SYMFONY_ENV: dev
    depends_on:
      - redis
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi-php.conf:/etc/nginx/conf.d/fastcgi-php.conf
    ports:
      - "8888:80"
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: queue_processing
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
