name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Check PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Quality Checks
        run: composer quality-ci

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit -c phpunit.xml.dist

      - name: Run Behat Tests
        run: vendor/bin/behat -c behat.yml.dist
