name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Check PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '>=20.10.0'

      - name: Install npm dependencies
        run: npm install --no-audit --no-fund

      - name: Run Quality Checks
        run: composer quality-ci
